### PR TITLE
temporary settings: Fix stale value issues with frequent updates

### PR DESCRIPTION
**Pull request by fkling**
This is more of an RFC/suggestion.

The temporary settings storage listens to changes from the backend and keeps a local copy of the data. When the data is updated the update is sent to the backend, the local copy is updated and subscribers are notified of the update.
Sending an update to the backend will cause all subscribers to be notified of the update after the backend processed it, including the subscriber that made the update.

This can cause issues if multiple updates happen in quick succession, something like:

```
subscriber        storage            backend
  |                  |                  |
  |                  |                  |
  | -- update A -->  |                  |
  | <-- notify A --  |                  |
  |                  | -- update A -->  | process A
  |                  |                  |
  | -- update B -->  |                  |
  | <-- notify B --  |                  |
  |                  | -- update B -->  | process A,B
  |                  |                  |
  |                  | <-- notify A --  | process B
  | <-- notify A --  |                  |             ! subscriber receives outdated data !
  |                  | <-- notify B --  |
  | <-- notify B --  |                  |
```

More specifically: The server backend uses Apollo's `watchQuery` to notify the storage about any changes. It looks like it's possible that Apollo's cache is update *after* another edit has already been made.

Interestingly I couldn't observe affecting this usage in React, even though I can see that the data returned by `useTemporarySetting` is stale. But I noticed this in the implementation I've worked on for the SvelteKit prototype.

**NOTE:** No idea whether this is the best way to solve the problem but it's at least backend independent. I think it should be fine to ignore updates while an edit is pending, since the storage has a local copy of the latest data, but this assumption is only true as long as storage is used as a singlton and the user isn't making changes at the same time on multiple devices.

## Test plan

Manual testing. Add `console.log` statements to a place that uses temporary settings (e.g. the search sidebar) and trigger frequent temporary settings updates (e.g. toggling sections quickly).

## App preview:

- [Web](https://sg-web-fkling-fix-temporary-settings.onrender.com/search)

Check out the [client app preview documentation](https://docs.sourcegraph.com/dev/how-to/client_pr_previews) to learn more.

### CODE REVIEW

**Comment by sg-e2e-regression-test-bob** [comment]
## Bundle size report 📦

| Initial size | Total size | Async size | Modules |
| --- | --- | --- | --- |
| 0.01% (+0.19 kb) | 0.00% (+0.19 kb) | 0.00% (0.00 kb) | 0.00% (0) |

Look at the [Statoscope report](https://console.cloud.google.com/storage/browser/_details/sourcegraph_reports/statoscope-reports/fkling/fix-temporary-settings/compare-report.html;tab=live_object) for a full comparison between the commits f68d020 and a96f3d3 or [learn more](https://docs.sourcegraph.com/dev/how-to/testing#bundlesize).


<details>
<summary>Open explanation</summary>

- `Initial size` is the size of the initial bundle (the one that is loaded when you open the page)
- `Total size` is the size of the initial bundle + all the async loaded chunks
- `Async size` is the size of all the async loaded chunks
- `Modules` is the number of modules in the initial bundle
</details>

**Review by limitedmage — APPROVED** [review]
This is an interesting bug and fix. I think it's ok, but wondering if other @sourcegraph/frontend-devs have any other suggestions here since I'm not super familiar with the internals of Apollo.

**Comment by vovakulikov** [comment]
@fkling I also think this should be fine to ignore updates when we're performing an update so it has my approval as well.

I think there is also one case when we perform A event and it's pending on the backend when we perform B and it's pending and got resolved on the backend and sent back to the client (so we open the update event semaphore that you've introduced in this PR) and then A gets resolved and since semaphore is open we perform it on the client, so we override the B (latest update) again. 

I don't have a good answer to solve this in our reality, in real world examples usually this is solved with more advanced methods like CRDT or Operational transformation but I think it's obviously an overkill for our needs (and even if we wanted to have something like this we don't have any transport for this, all our communication is a one way street, backend can't notify clients about changes so there is nothing that we can really do at the moment). 

What I can suggest is to introduce a temporary settings update version. We gonna have a version field in the settings that might be just an incremental int field and every time we perform an update we increment version, if we got settings from the backend that have version int less than we have on the client we can ignore this since this is probably an outdated response. 

But I think we need to have the backend part as well. Let's image I have two device in first device (A) I made a few updates and version is 100, my other device (B) has version 90, when I do some changes on my (B) device if we increment version on the client it will have 91 but the backend store settings with 100, so my next update from B should get 101 version instead.

**Comment by fkling** [comment]
@vovakulikov Yes, I was also thinking that having some kind of "ID" is more robust but requires server side changes. However I was only thinking about in the context of the update transaction itself.
I haven't looked at how temporary settings are actually stored on the serve side but I guess we could:
- Extend the GraphQL to store the current timestamp alongside `contents`.
- Store the current timestamp in the JSON payload itself.

I'll look at a bit more into this. @limitedmage do you have any preference out of these two solutions for storing an incremental ID?

**Comment by limitedmage** [comment]
We already have an "updated_at" column in the db, can we use that instead of storing the timestamp in the JSON?

**Comment by fkling** [comment]
@limitedmage I don't believe that works because that value is set on the server side. When the client gets the update notification for `A` it doesn't know whether that it's outdated.

**Comment by limitedmage** [comment]
The problem with setting a timestamp on the client side is that the user may have the wrong time on their system for whatever reason. We've seen this issue before in logs that add a client-side timestamp. So if a user has a misconfigured clock on one computer and not another, their temporary settings may not update correctly.

**Comment by vovakulikov** [comment]
@limitedmage True, we can't trust users timestamps. This is why I suggested using just incremental integer for the id. So in my mind it will be something like simplified version of any logical clock (I think the easiest one is [Lamport timestamp](https://en.wikipedia.org/wiki/Lamport_timestamp) algorithm)

**Comment by fkling** [comment]
@limitedmage, @vovakulikov Ah ok, I didn't consider that. Storing the counter as part of the JSON payload would allow us to use this approach regardless of the underlying storage system. What do you think?

**Comment by limitedmage** [comment]
Yeah let's give that a try. What do we do if a user updates settings on two computers at the same time? Would the server reject the update that comes last because it's duplicating a version number?

**Comment by fkling** [comment]
@limitedmage I don't think the server would do anything with the payload. It's purely a client side thing, or at least that's how I understood it. It's possible that updates get overwritten in this scenario but I think that's already the case. I'd assume it's also a highly unlikely scenario (though not impossible of course).

**Comment by limitedmage** [comment]
Sounds good!

**Pull request closed without merging**
