### PR TITLE
Fix Typo In cody.json File

### PR DESCRIPTION
**Pull request by shmuel44**
Fix typo issue in `.vscode/cody.json` file.
`commands` instead of `commandss`

issue number #58755 

## Test plan

n/a

### CODE REVIEW

**Comment by shmuel44** [comment]
@cla-bot check

**Comment by shmuel44** [comment]
@cla-bot check

**Comment by jdorfman** [comment]
Thanks @shmuel44! I will get this merged asap

**Review by unknwon — APPROVED** [review]

**Review by burmudar — APPROVED** [review]

**Comment by jdorfman** [comment]
@burmudar is this good to merge or close?

**Comment by burmudar** [comment]
> @burmudar is this good to merge or close?

This dropped of my radar - apologies. Just following up on why a recent change made this file empty and then we can see from there whether we'll merge or close :)

**Pull request closed without merging**
